### ISSUE TITLE
IOError: first argument must be an open file

### ISSUE THREAD

**Issue by chesstrian** [MrMinimal64/timezonefinder#66] opened 2018-12-06 20:38 UTC
Hi everyone, I'm using this library to get timezone from user addresses, I'm getting this error for the following coordinates:

`tf.timezone_at(lng=-87.6330737, lat=41.9112897)`

Can you help me please telling what it means in this case?, this seems a numpy issue, but not sure what's wrong in this case.

Thanks in advance.

**Comment by adamchainz** [comment] 2018-12-06 21:32
Please paste the traceback?

**Comment by chesstrian** [comment] 2018-12-07 14:38
@adamchainz Sorry for delay, somehow I missed the notification.

![image](https://user-images.githubusercontent.com/3923412/49653568-54d6a880-fa03-11e8-9520-8199a87ddd3a.png)

```
IOError                                   Traceback (most recent call last)
<ipython-input-45-2a15118102c3> in <module>()
----> 1 tf.timezone_at(lng=-87.6330737, lat=41.9112897)

/Users/christian/.venvs/mw/lib/python2.7/site-packages/timezonefinder/kwargs_only.pyc in wrapper(*args, **kwargs)
     30         if len(args) > allowable_args:
     31             raise TypeError("{} should only be called with keyword args".format(func.__name__))
---> 32         return func(*args, **kwargs)
     33
     34     return wrapper

/Users/christian/.venvs/mw/lib/python2.7/site-packages/timezonefinder/timezonefinder.pyc in timezone_at(self, lng, lat)
    505             return timezone_names[unpack(b'<H', self.shortcuts_unique_id.read(2))[0]]
    506         except IndexError:
--> 507             possible_polygons = self.polygons_of_shortcut(shortcut_id_x, shortcut_id_y)
    508             nr_possible_polygons = len(possible_polygons)
    509             if nr_possible_polygons == 0:

/Users/christian/.venvs/mw/lib/python2.7/site-packages/timezonefinder/timezonefinder.pyc in polygons_of_shortcut(self, x, y)
    203         self.shortcuts_adr2data.seek(1440 * x + 4 * y)
    204         self.shortcuts_data.seek(unpack(b'<I', self.shortcuts_adr2data.read(4))[0])
--> 205         return fromfile(self.shortcuts_data, dtype='<u2', count=nr_of_entries)
    206
    207     def coords_of(self, line=0):

IOError: first argument must be an open file
```

**Comment by MrMinimal64** [comment] 2018-12-07 15:01
Thanks for reporting this. Unfortunately I cannot reproduce your error (neither with Python3.7 nor 2.7). From the error message I am guessing that somehow the binary file ("shortcut_data.bin") is not being kept open while you keep your Timezonefinder class instance alive. Does this happen with all coordinates? Please try to create a new class instance and repeat the command.

**Comment by chesstrian** [comment] 2018-12-07 15:21
Really weird, it happens on Heroku and I can reproduce it in my Mac, it does not happen with all coordinates, just a few of them, I also can reproduce it by creating a new instance.

**Comment by MrMinimal64** [comment] 2018-12-09 17:34
That is indeed strange! Can anyone else reproduce this error or identify the cause of this issue?

**Comment by MrMinimal64** [comment] 2019-02-03 21:19
Thanks for reporting. I found this Issue: https://github.com/numpy/numpy/issues/6246

Could you please try to replace the line

` return fromfile(self.shortcuts_data, dtype='<u2', count=nr_of_entries)        `

with 

```
from numpy import frombuffer
print(self.shortcuts_data.closed)
return frombuffer(self.shortcuts_data.read(2 * nr_of_entries), '<u2')
```

and check if the error persists?
Thanks. Maybe this issue is being automatically resolved by dropping python2 support.

**Comment by khargy** [comment] 2019-02-03 22:40
Ok, I installed Python3 on my Mac (3.7.2) and the error goes away. I added your test code to both versions... 

The Python3 prints a "False" for the print statement...
```
False
America/Edmonton
```

I still get the error on the Python2 version and the test print is also False
```
False
Traceback (most recent call last):
  File "gpx2.py", line 124, in <module>
    main(sys.argv[1:])
  File "gpx2.py", line 36, in main
    test = tf.timezone_at(lng=-118, lat=52)
  File "/Library/Python/2.7/site-packages/timezonefinder/kwargs_only.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/timezonefinder/timezonefinder.py", line 456, in timezone_at
    boundaries = fromfile(self.poly_max_values, dtype=DTYPE_FORMAT_SIGNED_I_NUMPY, count=4)
```

**Comment by MrMinimal64** [comment] 2019-02-08 21:57
Ok, thanks for trying. It seems as if #72 would resolve this issue. Lets see if this error persists with the coming release

**Comment by MarkWilliamMatthews** [comment] 2019-02-25 11:44
Hi, I am also getting this error (Python 2.7.14, Debian GNU/Linux) with these co-ordinates:

    tf.timezone_at(lng=151.261300407, lat=-29.383656596)

Traceback:  

    File "/home/web/django_project/processing/tools/processor.py", line 431, in set_dam_timezone
    self.timezone_name = tf.timezone_at(lng=lon, lat=lat)  # Returns timezone string
    File "/usr/local/lib/python2.7/site-packages/timezonefinder/kwargs_only.py", line 32, in wrapper
    return func(*args, **kwargs)
    File "/usr/local/lib/python2.7/site-packages/timezonefinder/timezonefinder.py", line 427, in timezone_at
    possible_polygons = self.polygon_ids_of_shortcut(shortcut_id_x, shortcut_id_y)
    File "/usr/local/lib/python2.7/site-packages/timezonefinder/timezonefinder.py", line 126, in polygon_ids_of_shortcut
    return fromfile(self.shortcuts_data, dtype=DTYPE_FORMAT_H_NUMPY, count=nr_of_entries)
    IOError: first argument must be an open file

It works for other very similar coordinates - weird. I haven't yet tried @MrMinimal64's patch above. Will reverting to earlier release solve it?

**Comment by MrMinimal64** [comment] 2019-02-25 12:53
I am afraid the most promising workaround is changing to Python3 (future releases will actually only support python3 anyway). The patch above did not seem to work and using earlier releases also means using outdated data.

**Comment by MarkWilliamMatthews** [comment] 2019-02-25 13:22
Since accuracy is not critical for my application at the moment, my solution was to use timezonfinderL until I find time to upgrade my app to Python 3. Thanks @MrMinimal64

**Comment by MrMinimal64** [comment] 2019-03-12 19:17
Please check if the error persists with the new version v4.0.0

**Closed** 2019-03-14 20:12 UTC
Labels: help wanted, wontfix
