### ISSUE TITLE
How much faster are you than pytzwhere?

### ISSUE THREAD

**Issue by cstich** [MrMinimal64/timezonefinder#30] opened 2016-04-22 12:28 UTC
Do you have any idea how much faster you are than [pytzwhere](https://github.com/pegler/pytzwhere) when using shapely with pytzwhere?

I like your usage of numba though. That makes a lot of sense :)

**Comment by MrMinimal64** [comment] 2016-04-22 12:35
I'll check.

**Comment by cstich** [comment] 2016-04-22 12:41
Both if it is not too much to ask.

**Comment by MrMinimal64** [comment] 2016-04-22 12:43
I guess it makes not sense to compare it without Numba :D. (s. above)

**Comment by cstich** [comment] 2016-04-22 13:00
Nice. Also how do you feel about potentially merging the two projects? It is totally up to you but you did implement a few things that I had in mind for the next version of pytzwhere already (reading from a binary file, working on the lookup hack, etc.)

**Comment by MrMinimal64** [comment] 2016-04-22 13:17
Generally I am open to that since the cause (open source offline timezone localisation) would benefit. I quickly thought about integrating ``shapely`` in timezonefinder, though, and I am not really sure yet if that makes sense. With pytzwhere you construct every polygon for shapely on the startup every time, but with my approach you would need to create the shapely polygons for every polygon again and again (when reading data from .bin). I don't know how fast this is, but in total it might not save that much time after all. So I guess maybe some features cannot be merged just that easily...

**Comment by cstich** [comment] 2016-04-22 13:24
What I thought about doing with the `shapely` polygons is lazily construct them. You really only need to construct a `shapely` polygon the first time you deal with that polygon and then you can cache it.

**Comment by cstich** [comment] 2016-04-22 13:31
I will just implement that and issue a pull request. I have some time during the first weekend of May. Would that work for you?

**Comment by MrMinimal64** [comment] 2016-04-22 13:38
Yes, cool. I have never worked with caching in Python so I would definitely appreciate the help. The problem is that I store my polygons like this atm: [x1,x2,x3...][y1,y2,y3,...]
This just made sense for me. I guess rearranging these arrays would take additional time.
Do you think you can work with the ``.bin``? I imagine it to be hard to understand.

**Comment by cstich** [comment] 2016-04-22 13:47
I think I am going to be fine using the `.bin`. And the array [x1, x2, x3, ..] [y1,y2,y3,..] makes sense. I think I have to iterate over the array once to get a tuple of (x, y) for shapely but it shouldn't really affect performance that much if I get the caching to work :D

**Comment by MrMinimal64** [comment] 2016-04-22 13:47
please write me a mail so we can further discuss if any issues come up:
python at michelfe dot it

**Comment by cstich** [comment] 2016-04-22 13:48
Will do

**Closed** 2016-04-22 15:42 UTC
